/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VNgQlNlmFOZ
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { DropdownMenuTrigger, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import Image from 'next/image'

export function Dashboard() {
  return (
    (<Card>
      <CardHeader className="pb-0">
        <CardTitle>Thumbnail Generator</CardTitle>
        <CardDescription>Create stunning thumbnails for your posts.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="grid gap-2">
          <label className="text-sm font-medium" htmlFor="upload">
            Upload Image
          </label>
          <div
            className="border-2 border-dashed border-gray-200 rounded-lg p-4 flex items-center justify-center w-full h-[200px]">
            <UploadIcon className="w-6 h-6" />
            <span className="text-gray-500 font-medium">
              Drag and drop your image here or
              <Button size="sm" variant="ghost">
                Browse
              </Button>
            </span>
          </div>
        </div>
        <div className="grid gap-2">
          <label className="text-sm font-medium" htmlFor="text">
            Add Text
          </label>
          <Input
            className="w-full"
            id="text"
            placeholder="Enter text to include in the thumbnail" />
        </div>
        <div className="grid gap-2">
          <label className="text-sm font-medium">Brand</label>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button className="!rounded-lg !text-left w-full" id="style" variant="outline">
                Classic
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent>
              <DropdownMenuItem>Modern</DropdownMenuItem>
              <DropdownMenuItem>Classic</DropdownMenuItem>
              <DropdownMenuItem>Elegant</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
        <div className="grid gap-2">
          <label className="text-sm font-medium">Theme</label>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button className="!rounded-lg !text-left w-full" id="theme" variant="outline">
                Corporate
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent>
              <DropdownMenuItem>Corporate</DropdownMenuItem>
              <DropdownMenuItem>Casual</DropdownMenuItem>
              <DropdownMenuItem>Playful</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
        <Button className="w-full">Generate Thumbnail</Button>
        <div className="border border-gray-200 rounded-lg p-4">
          <Image
            alt="Generated Thumbnail"
            className="object-cover w-full h-48"
            height={200}
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/200",
              objectFit: "cover",
            }}
            width={400} />
        </div>
      </CardContent>
    </Card>)
  );
}


function UploadIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M21 15v4a2 2 0 1-2 2H5a2 1-2-2v-4" />
      <polyline points="17 8 12 3 7" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>)
  );
}
